### ISSUE TITLE
Error generating the model

### ISSUE THREAD

**Issue by cufano** [simialbi/yii2-schema-org#1]
Hello, when generating the model with
#php yii schema/schema-org

I get this error:

Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Application::schema'

**Comment by simialbi** [comment]
How does your `config/console.php` respectively your `console/config/main.php` looks like?

**Comment by cufano** [comment]
Hello @simialbi thnak you for your response, I was using the console/config/main-local.php instead of console/config/main.php for setting the configuration. Now I changed it to main.php and all models have been generated
