### ISSUE TITLE
Error creating models for Schema.org version from 3.5

### ISSUE THREAD

**Issue by cufano** [simialbi/yii2-schema-org#7]
Hello, from version 3.5 of Schema.org definition, the current creating models process is not running because the schema.org definition JSON file has changed.

**Comment by simialbi** [comment]
You are right, this code changed in the [2.0.2 release](https://github.com/simialbi/yii2-schema-org/releases). To support both is IMHO not very useful. If you need the old release of schema org, use the `2.0.1` release.
